### ISSUE TITLE
Object.observe undefined

### ISSUE THREAD

**Issue by rickdog** [anywhichway/joqular#10]
You need a shim for Firefox, IE & Safari: Object.observe is an ECMA 7 proposal

joqular runs with the polyfill
https://github.com/MaxArt2501/object-observe/blob/master/dist/object-observe.js

**Comment by anywhichway** [comment]
Thank you. This is already documented close to the bottom of the Wiki home page under the section Compatibility. Since you have identified a specific polyfill, we have added this to the documentation.
