### ISSUE TITLE
Feature enquiry

### ISSUE THREAD

**Issue by Offirmo** [anywhichway/joqular#14]
This looks very nice, but why forcing us to use classes ? Couldn't we just provide an array of hashes ?

``` js
const data = [ { name: 'John', age: 34 },  { name: 'Jack', age: 42 } ]
const db = joqular(data)
db.find(data, {age: {$gte: 40}})
```

That would be non-intrusive and super cool !

**Comment by anywhichway** [comment]
The classes are used so that separate indexes can be maintained and objects joined with each other like in a relational database. The version about to be released with support plain objects in addition to classes.

**Comment by Offirmo** [comment]
great :+1:

**Comment by anywhichway** [comment]
A replacement for JOQULAR, ReasonDB, has been published on npm and is available at https://github.com/anywhichway/reasondb.
