### ISSUE TITLE
development status

### ISSUE THREAD

**Issue by Offirmo** [anywhichway/joqular#15]
Also, is this lib actively developed / maintained ?

It looks great...

**Comment by anywhichway** [comment]
We are actively working on an enhancement replacement that will include streaming analytics, browser and server persistence (with pluggable Redis and other stores) and the same core query language. We hope to push a release this weekend. We will re-post to this issue when we do so. The upgrade has been a long time coming because we wanted to take advantage of the latest ES6/7 features while also making the code base far smaller.

**Comment by Offirmo** [comment]
great :+1: Looking forward it ! (Also looking forward doc and examples ;)

meanwhile, I'm also evaluating http://www.js-data.io/

If you have opinions on differences and compared shine point, I'm interested.

**Comment by anywhichway** [comment]
You will find lots of documentation here: https://github.com/anywhichway/joqular/wiki/

Suggest you start with: https://github.com/anywhichway/joqular/wiki/JOQULAR-Patterns

Do direct comparison with js-data at this time.

**Comment by Offirmo** [comment]
I visited those links already: they say "This Wiki is for Version 1 of JOQULAR"...

**Comment by anywhichway** [comment]
The capability is very similar from a query perspective. The query predicates are now all prefixed with $. Projections are now supported. The internals have changed dramatically, currently at under 40K un-minimized. The approach to extending JOQULAR has been simplified and streaming analytics has been added. With respect to js-data, we do not have as many adapters built at this time, but they are easy to develop and the approach will be documented. We will not be releasing schema validation yet, but we have fully operational code internally. We are pushing hard for this weekend.

**Comment by Offirmo** [comment]
Looking forward to it !

Don't push yourself too much, I'm just doing a hobby project ^^

**Comment by Offirmo** [comment]
~passing by~ :dancing_women:

**Comment by anywhichway** [comment]
The first release of ReasonDB, the new name for JOQULAR has been pushed to the npm registry and is available at https://github.com/anywhichway/reasondb.
