### ISSUE TITLE
Add Insert, Delete, Update SQL Like Capability

### ISSUE THREAD

**Issue by anywhichway** [anywhichway/joqular#9]
This is on track for early June.

**Comment by cag-oss** [comment]
make these operations immutable! On update/insert/delete, create new refrences for the portion of the tree that was modified. On Query, return references to object such that strict equality holds for the same query (assuming no select/data shaping). Also, make sure this works over plain json without having to create and intermediary class. But it looks like it does/will. Great library, looking forward to the next release!

**Comment by anywhichway** [comment]
Thanks for the comment and support. We are working hard on the next release. Currently the new references are only created if the object being inserted is not an instanceof the class being aliased. For example JOQULAR.Insert({name: 'Bill'}).into({p1: Person}) mutates the object whereas var p = new Person(); p.name = 'Bill'; JOQULAR.insert(p).into({p1: Person}) does not. We have to mutate the first object to get what be believe are correct semantics for Select, i.e. if your Select from Person your should only get Persons back. We have reviewed the code and this appears correct for the designed behavior and we will add a unit test to verify with the next release. We are open to discussion and debate to the correct design approach.

With respect to plain JSON, it can't be used to transport Infinity and NaN without creating mutated sub-classes or values as placeholders, so it is a bit problematic. We have a plugin replacement similar to JSON5 to address this. We are committed to NOT creating something like BSON. When data is transported, the plan is to transport it as {instance: <some object>, metadata: {kind: "<some class name", id: "<some id>"}}. This way the server will be able to create proper instances for isomorphic programming.

We have a delay in the next release because Google yanked Proxies from from the v8 engine and we had some designs that depended on them. We expect to have this resolved by the end of August now. Sorry for the delay.

**Comment by anywhichway** [comment]
NOTE: Version 2.0 of JOQULAR was about to be released November 15th, 2015 when it was announced Object.observe is being dropped from the ECMA standards track. This will require re-working certain portions of JOQULAR. Hence, there will be a delay. However, it is recommended you not start using this version for anything other than exploratory investigation. The new version of JOQULAR has the following:

1) A far cleaner code-base
2) A more modular code-base
3) Supports schema based validation on a continuous basis per property change or a per Object invocation
4) Supports both client and server storage with synchronization

**Comment by anywhichway** [comment]
A replacement for JOQUALR, ReasonDB, has been published on npm and is available at https://github.com/anywhichway/reasondb.
